name: KritikAI
on:
  pull_request:
    types: [opened]
jobs:
  kritikai:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: KritikAI code review
        uses: Kritik-ai/workflow@0.0.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          kritik-token: ${{ secrets.KRITIK_TOKEN }}
